<?php

/**
 * This file is part of ZeroBoiler, licensed under the proprietary license.
 */

declare(strict_types=1);

namespace ZeroBoiler\DTO\Attributes;

use Attribute;

/**
 * Exclude a property from public serialization output.
 *
 * A metadata-only attribute (does not implement {@see \ZeroBoiler\DTO\Contracts\ValidationAttribute}).
 * Hidden properties are still accessible on the DTO instance itself
 * and included in {@see \ZeroBoiler\DTO\DataTransferObject::allValues()} output.
 * Only the public serialization methods
 * ({@see \ZeroBoiler\DTO\DataTransferObject::toArray()},
 * {@see \ZeroBoiler\DTO\DataTransferObject::toJson()},
 * {@see \ZeroBoiler\DTO\DataTransferObject::jsonSerialize()})
 * respect this attribute. The property is also excluded from OpenAPI schema output
 * generated by {@see \ZeroBoiler\DTO\Support\OpenApiSchemaGenerator}.
 *
 *   #[Hidden]
 *   public readonly string $password;
 *
 * This attribute has no constructor parameters.
 *
 * @see \ZeroBoiler\DTO\Attributes\MapFrom For source key aliasing (metadata attribute)
 * @see \ZeroBoiler\DTO\Attributes\Cast For type casting (metadata attribute)
 * @see \ZeroBoiler\DTO\Attributes\DefaultValue For default value (metadata attribute)
 */
#[Attribute(Attribute::TARGET_PROPERTY)]
final class Hidden {}
